import { Language } from '@/types';

export const TRANSLATIONS = {
  en: {
    appTitle: 'Civic Radar TN',
    dashboard: 'Dashboard',
    reportIssue: 'Report Issue',
    myReports: 'My Reports',
    analytics: 'Analytics',
    settings: 'Settings',
    login: 'Login',
    logout: 'Logout',
    submit: 'Submit Report',
    description: 'Description',
    location: 'Location',
    analyzing: 'AI Analyzing...',
    status: 'Status',
    urgency: 'Urgency',
    category: 'Category',
    switchRole: 'Switch Role (Demo)',
    welcome: 'Welcome, Citizen',
    welcomeAdmin: 'Welcome, Administrator',
    recentActivity: 'Recent Activity',
    issueDistribution: 'Issue Distribution',
    trendAnalysis: 'Trend Analysis',
    aiInsight: 'AI Insight',
    noReports: 'No reports submitted yet.',
    enterDescription: 'Describe the issue (e.g., "Big pothole on Anna Salai")',
    reports: 'Reports',
    resolved: 'Resolved',
    pending: 'Pending',
    critical: 'Critical',
  },
  ta: {
    appTitle: 'குடிமை ரேடார் த.நா',
    dashboard: 'தரவுப் பலகை',
    reportIssue: 'புகார் அளிக்கவும்',
    myReports: 'எனது புகார்கள்',
    analytics: 'பகுப்பாய்வு',
    settings: 'அமைப்புகள்',
    login: 'உள்நுழைய',
    logout: 'வெளியேறு',
    submit: 'சமர்ப்பிக்கவும்',
    description: 'விளக்கம்',
    location: 'இடம்',
    analyzing: 'AI ஆய்வு செய்கிறது...',
    status: 'நிலை',
    urgency: 'அவசர நிலை',
    category: 'வகை',
    switchRole: 'பாத்திரத்தை மாற்றவும்',
    welcome: 'வணக்கம், குடிமகன்',
    welcomeAdmin: 'வணக்கம், நிர்வாகி',
    recentActivity: 'சமீபத்திய செயல்பாடுகள்',
    issueDistribution: 'புகார் விநியோகம்',
    trendAnalysis: 'போக்கு பகுப்பாய்வு',
    aiInsight: 'AI நுண்ணறிவு',
    noReports: 'இதுவரை எந்த புகாரும் இல்லை.',
    enterDescription: 'பிரச்சனையை விவரிக்கவும்',
    reports: 'புகார்கள்',
    resolved: 'தீர்க்கப்பட்டது',
    pending: 'நிலுவையில்',
    critical: 'மிக முக்கியம்',
  }
};

export const MOCK_ISSUES = [
  {
    id: '1',
    title: 'Water Leakage in T. Nagar',
    description: 'Main pipe burst near the bus terminus.',
    category: 'Water Supply',
    urgency: 'High',
    status: 'Open',
    location: 'T. Nagar, Chennai',
    timestamp: Date.now() - 86400000,
  },
  {
    id: '2',
    title: 'Street Light Broken',
    description: 'Dark street causing safety issues.',
    category: 'Electricity',
    urgency: 'Medium',
    status: 'Resolved',
    location: 'Gandhipuram, Coimbatore',
    timestamp: Date.now() - 172800000,
  },
  {
    id: '3',
    title: 'Garbage Pileup',
    description: 'Waste not collected for 3 days.',
    category: 'Sanitation',
    urgency: 'High',
    status: 'In Progress',
    location: 'Madurai Main Rd',
    timestamp: Date.now() - 43200000,
  }
];
