export const labelsTa = {
    appTitle: 'குடிமை ரேடார் த.நா',
    dashboard: 'கண்ணோட்டம்',
    reportIssue: 'குறை தீர்க்க',
    myReports: 'எனது புகார்கள்',
    analytics: 'பகுப்பாய்வு',
    settings: 'அமைப்புகள்',
    login: 'உள்நுழைய',
    logout: 'வெளியேறு',
    submit: 'அனுப்புக',
    description: 'என்ன பிரச்சனை?',
    location: 'எந்த இடம்?',
    analyzing: 'படிக்கிறது...',
    status: 'நிலை',
    urgency: 'அவசரம்',
    category: 'வகை',
    switchRole: 'முறை மாற்று',
    welcome: 'வணக்கம்',
    welcomeAdmin: 'வணக்கம், நிர்வாகி',
    recentActivity: 'சமீபத்திய செயல்பாடுகள்',
    issueDistribution: 'புகார் விநியோகம்',
    trendAnalysis: 'போக்கு பகுப்பாய்வு',
    aiInsight: 'AI உதவி',
    noReports: 'இதுவரை எந்த புகாரும் இல்லை.',
    enterDescription: 'எ.கா., தெரு குழாயில் தண்ணீர் இல்லை',
    reports: 'புகார்கள்',
    resolved: 'சரிசெய்யப்பட்டது',
    pending: 'நிலுவையில்',
    critical: 'மிக முக்கியம்',
    sectors: 'துறைகள்',
    policies: 'கொள்கைகள்',
    alerts: 'எச்சரிக்கைகள்',
    datasets: 'தரவுத்தொகுப்புகள்',

    // Citizen Navigation
    home: 'முகப்பு',
    schemes: 'அரசு நலத்திட்டங்கள்',
    eligibility: 'தகுதிச் சோதனை',
    howToApply: 'விண்ணப்பிப்பது எப்படி',

    // Schemes Page
    scheme_midday: 'சத்துணவுத் திட்டம்',
    scheme_midday_desc: 'பள்ளி மாணவர்களுக்கு இலவச மதிய உணவு.',
    scheme_pds: 'நியாய விலைக் கடை (ரேஷன்)',
    scheme_pds_desc: 'அரிசி, சர்க்கரை மற்றும் எண்ணெய் குறைந்த விலையில்.',
    scheme_scholarship: 'மாணவர் உதவித்தொகை',
    scheme_scholarship_desc: 'கல்லூரி மாணவர்களுக்கான பண உதவி.',
    learnMore: 'மேலும் அறிய',

    // Eligibility Page
    check_eligibility_title: 'நான் தகுதியானவனா?',
    check_eligibility_desc: '3 கேள்விகளுக்கு பதிலளிக்கவும்.',
    age: 'வயது',
    income: 'ஆண்டு குடும்ப வருமானம் (₹)',
    occupation: 'தொழில்',
    check_btn: 'சோதிக்கவும்',
    eligible_msg: 'உங்களுக்கு கிடைக்கக்கூடியவை:',
    not_eligible_msg: 'தகுதியான திட்டங்கள் எதுவும் காணப்படவில்லை.',

    // How to Apply
    steps_title: 'விண்ணப்பிக்கும் முறை',
    step_1: 'ஆவணங்களைச் சேகரிக்கவும்',
    step_2: 'அலுவலகம் / இணையதளத்திற்குச் செல்லவும்',
    step_3: 'விண்ணப்பத்தை சமர்ப்பிக்கவும்',
    docs_needed: 'தேவையான ஆவணங்கள்:',
    aadhaar: 'ஆதார் அட்டை',
    ration: 'ரேஷன் அட்டை',
    income_cert: 'வருமான சான்றிதழ்',

    // Report Issue
    report_title: 'பிரச்சினையை சொல்லுங்கள்',
    report_subtitle: 'இதை சரியான அதிகாரியிடம் கொண்டு சேர்ப்போம்.',
    ai_category_detect: 'இது எதைப் பற்றியது:',
    ai_urgency_detect: 'முக்கியத்துவம்:',

    // Admin Navigation
    ingestion: 'தரவு உட்செலுத்துதல்',
    baseline: 'அடிப்படை அளவுகள்',
    deviations: 'விலகல்கள்',
    nlp: 'மொழி ஆய்வு',
    fusion: 'ஒருங்கிணைப்பு',

    // Admin Common
    advancedSettings: 'மேம்பட்ட அமைப்புகள்',
    exportReport: 'அறிக்கை ஏற்றுமதி',
    period: 'காலம்',
    region: 'மாவட்டம்',
    filter: 'வடிகட்டி',
    lastUpdated: 'கடைசியாக புதுப்பிக்கப்பட்டது',
    totalRecords: 'மொத்த பதிவுகள்',
    score: 'சுகாதார மதிப்பெண்',
    confidence: 'நம்பிக்கை',
    evidence: 'ஆதாரம்',
    actions: 'செயல்கள்',
    upload: 'பதிவேற்றம்'
};