'use client';

import React, { useState } from 'react';
import { AlertTriangle, CheckSquare, Eye, XOctagon, Clock, MapPin } from 'lucide-react';
import AppShell from '@/components/AppShell';
import { useAuthStore } from '@/lib/auth';
import { labelsEn } from '@/config/labels.en';
import { labelsTa } from '@/config/labels.ta';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

export default function AlertsPage() {
  const { language } = useAuthStore();
  const t = language === 'en' ? labelsEn : labelsTa;

  // Mock Alerts
  const [alerts] = useState([
    { id: 'ALT-102', severity: 'Critical', title: 'Civil Supplies Crisis', location: 'Coimbatore', time: '2h ago', status: 'New' },
    { id: 'ALT-099', severity: 'High', title: 'Midday Meal Quality Drop', location: 'Madurai', time: '5h ago', status: 'Ack' },
    { id: 'ALT-098', severity: 'Medium', title: 'Scholarship Portal Down', location: 'Statewide', time: '1d ago', status: 'Resolved' },
  ]);

  return (
    <AppShell>
      <div className="space-y-6 max-w-7xl mx-auto">
        
        {/* Header */}
        <div>
            <h1 className="text-3xl font-extrabold tracking-tight text-slate-900">{t.alerts}</h1>
            <p className="text-slate-500 mt-1">Real-time alerts generated by the Fusion Engine requiring attention.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Alert List */}
            <div className="md:col-span-2 space-y-4">
                {alerts.map((alert) => (
                    <Card key={alert.id} className="hover:shadow-md transition-all cursor-pointer group border-l-4 overflow-hidden" style={{
                         borderLeftColor: alert.severity === 'Critical' ? '#ef4444' : alert.severity === 'High' ? '#f97316' : '#eab308'
                    }}>
                        <CardContent className="p-6">
                            <div className="flex flex-col sm:flex-row justify-between items-start gap-4">
                                 <div className="flex gap-4">
                                     <div className={`p-3 rounded-xl h-fit shadow-sm flex-shrink-0 ${
                                         alert.severity === 'Critical' ? 'bg-red-50 text-red-600' :
                                         alert.severity === 'High' ? 'bg-orange-50 text-orange-600' : 'bg-yellow-50 text-yellow-600'
                                     }`}>
                                         <AlertTriangle className="w-6 h-6" />
                                     </div>
                                     <div>
                                         <div className="flex flex-wrap items-center gap-2 mb-1">
                                             <h3 className="font-bold text-slate-800 text-lg group-hover:text-tn-700 transition-colors">{alert.title}</h3>
                                             <Badge variant="outline" className="text-[10px] text-slate-400 font-mono bg-slate-50">#{alert.id}</Badge>
                                         </div>
                                         <div className="flex items-center gap-4 text-sm text-slate-500 mt-1">
                                             <span className="flex items-center gap-1.5"><MapPin className="w-3.5 h-3.5" /> {alert.location}</span>
                                             <span className="flex items-center gap-1.5"><Clock className="w-3.5 h-3.5" /> {alert.time}</span>
                                         </div>
                                         <div className="mt-3">
                                            <Badge variant="secondary" className="bg-slate-100 text-slate-600 font-medium hover:bg-slate-200">
                                                Severity: {alert.severity}
                                            </Badge>
                                         </div>
                                     </div>
                                 </div>
                                 <div className="flex flex-row sm:flex-col items-center sm:items-end gap-3 w-full sm:w-auto mt-2 sm:mt-0 justify-between sm:justify-start">
                                     <Badge className={`${
                                         alert.status === 'New' ? 'bg-red-500 hover:bg-red-600' : 
                                         alert.status === 'Resolved' ? 'bg-green-500 hover:bg-green-600' : 'bg-blue-500 hover:bg-blue-600'
                                     }`}>
                                         {alert.status}
                                     </Badge>
                                     <Button variant="ghost" size="sm" className="text-tn-600 hover:text-tn-700 hover:bg-tn-50 p-0 h-auto font-medium">
                                         View Evidence
                                     </Button>
                                 </div>
                            </div>
                        </CardContent>
                    </Card>
                ))}
            </div>

            {/* Quick Actions / Stats */}
            <div className="space-y-6">
                <Card>
                    <CardHeader className="pb-4 border-b border-slate-100">
                        <CardTitle className="text-lg">Alert Stats (24h)</CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-6 pt-6">
                        <div>
                            <div className="flex justify-between items-center mb-2">
                                <span className="text-slate-600 text-sm font-medium">New Alerts</span>
                                <span className="font-bold text-slate-900">12</span>
                            </div>
                            <div className="w-full bg-slate-100 rounded-full h-2">
                                <div className="bg-red-500 h-2 rounded-full shadow-[0_0_10px_rgba(239,68,68,0.5)]" style={{ width: '40%' }}></div>
                            </div>
                        </div>
                        
                        <div>
                            <div className="flex justify-between items-center mb-2">
                                <span className="text-slate-600 text-sm font-medium">Acknowledged</span>
                                <span className="font-bold text-slate-900">8</span>
                            </div>
                             <div className="w-full bg-slate-100 rounded-full h-2">
                                <div className="bg-blue-500 h-2 rounded-full" style={{ width: '30%' }}></div>
                            </div>
                        </div>

                        <div className="pt-4 border-t border-slate-100 flex justify-between items-center">
                            <span className="text-slate-600 text-sm font-medium">Avg Response Time</span>
                            <span className="font-bold text-slate-900 font-mono text-lg">45m</span>
                        </div>
                    </CardContent>
                </Card>

                <Card className="bg-slate-50/50 border-slate-200">
                    <CardHeader className="pb-3">
                        <CardTitle className="text-base text-slate-800">Automated Actions</CardTitle>
                        <CardDescription>System triggered policy protocols.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-3">
                        <div className="flex items-center text-sm text-slate-700 bg-white p-2.5 rounded border border-slate-200 shadow-sm">
                            <CheckSquare className="w-4 h-4 mr-2 text-green-600 shrink-0" />
                            Notify District Collector (Critical)
                        </div>
                        <div className="flex items-center text-sm text-slate-700 bg-white p-2.5 rounded border border-slate-200 shadow-sm">
                            <CheckSquare className="w-4 h-4 mr-2 text-green-600 shrink-0" />
                            Email Sector Head (High+)
                        </div>
                        <div className="flex items-center text-sm text-slate-400 px-2.5">
                            <XOctagon className="w-4 h-4 mr-2 shrink-0" />
                            Auto-shutdown (Disabled)
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>
      </div>
    </AppShell>
  );
}